services:
  code:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: code
    volumes:
      - ./code:/home/code
      # be careful. don't use a bin that other things are installing into during
      # build or it will overwrite when mounting. why we don't use /go/bin
      - ./bin:/usr/local/bin
    working_dir: /home/code
    networks:
      - app-tier
# mysql and postresql services copied and adjusted from sqlc
# https://github.com/sqlc-dev/sqlc/blob/main/docker-compose.yml
# https://docs.sqlc.dev/en/latest/guides/development.html
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: dinotest
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_ROOT_HOST: '%'
    networks:
      - app-tier
  postgresql:
    image: "postgres:16"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
