// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http). DO NOT EDIT.

package main

import (
	"database/sql"
	"net/http"

	author_app "mymodule/internal/author"
)

func registerHandlers(mux *http.ServeMux, db *sql.DB) {
	authorService := author_app.NewService(author_app.New(db))
	authorService.RegisterHandlers(mux)
}
