// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64       `db:"id"`
	Name string      `db:"name"`
	Bio  pgtype.Text `db:"bio"`
}
