// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http).

package main

import (
	"context"
	"database/sql"
	_ "embed"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"runtime"
	"syscall"
	"time"

	"github.com/XSAM/otelsql"
	"github.com/exaring/otelpgx"
	"github.com/flowchartsman/swaggerui"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	semconv "go.opentelemetry.io/otel/semconv/v1.23.0"
	"go.uber.org/automaxprocs/maxprocs"
	// database driver
	_ "github.com/jackc/pgx/v5/pgxpool"

	"my-project/internal/server/instrumentation/metric"
	"my-project/internal/server/instrumentation/trace"
	"my-project/internal/server/litefs"
	"my-project/internal/server/litestream"
)

const serviceName = "my-project"

var (
	dbURL string
	port  int

	//go:embed openapi.yml
	openAPISpec []byte
)

func main() {
	var dev bool
	flag.StringVar(&dbURL, "db", "", "The Database connection URL")
	flag.IntVar(&port, "port", 5000, "The server port")

	flag.BoolVar(&dev, "dev", false, "Set logger to development mode")

	flag.Parse()

	initLogger(dev)

	if err := run(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		slog.Error("server error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	_, err := maxprocs.Set()
	if err != nil {
		slog.Warn("startup", "error", err)
	}
	slog.Info("startup", "GOMAXPROCS", runtime.GOMAXPROCS(0))

	db, err := pgxpool.New(context.Background(), dbURL)
	if err != nil {
		return err
	}
	defer db.Close()

	mux := http.NewServeMux()
	registerHandlers(mux, db)
	mux.Handle("/swagger/", http.StripPrefix("/swagger", swaggerui.Handler(openAPISpec)))

	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: mux,
		// Please, configure timeouts!
	}

	done := make(chan os.Signal, 1)
	signal.Notify(done, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		sig := <-done
		slog.Warn("signal detected...", "signal", sig)
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		server.Shutdown(ctx)
	}()
	slog.Info("Listening...", "port", port)
	return server.ListenAndServe()
}

func initLogger(dev bool) {
	var handler slog.Handler
	opts := slog.HandlerOptions{
		AddSource: true,
	}
	switch {
	case dev:
		handler = slog.NewTextHandler(os.Stderr, &opts)
	default:
		handler = slog.NewJSONHandler(os.Stderr, &opts)
	}

	logger := slog.New(handler)
	slog.SetDefault(logger)
}
