openapi: 3.0.3
info:
  description: my-project Services
  title: my-project
  version: 0.0.1
  contact:
    name: sqlc-http
    url: https://github.com/walterwanderley/sqlc-http
tags:
  - db
  
paths:
  /author:
    post:
      tags:
        - db
      summary: CreateAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                bio:
                  type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Author"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    put:
      tags:
        - db
      summary: UpdateAuthor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                bio:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                name:
                  type: string
                bio:
                  type: string
      
      responses:
        "200":
          description: OK
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /author/{id}:
    delete:
      tags:
        - db
      summary: DeleteAuthor
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    get:
      tags:
        - db
      summary: GetAuthor
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Author"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /authors:
    get:
      tags:
        - db
      summary: ListAuthors
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Author"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  
components:
  schemas:
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        bio:
          type: string
    
  
