// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http). DO NOT EDIT.

package main

import (
	"database/sql"
	"net/http"

	"github.com/jackc/pgx/v5/pgxpool"

	db_app "my-project/internal/db"
)

func registerHandlers(mux *http.ServeMux, db *pgxpool.Pool) {
	dbService := db_app.NewService(db_app.New(db))
	dbService.RegisterHandlers(mux)
}
